# Updated Recursive Mock Gateway Configuration
# 
# This YAML file documents the configuration for the assistant REST API integration.
# 
# Integration Flow:
# - The client, via client-merit-instructional-flow.js, initiates an end-to-end chat session through an initial auto-volley request.
# - This request communicates with the assistant REST API endpoint (e.g., /api/v1/assistant/chat) using a preconfigured project/assistant pair.
# - The system provides context-aware responses by loading user context on the backend and attaching it to the session.
# - All interactions with Redis (for context caching, TTL management, etc.) are handled exclusively on the backend. The frontend does not interact with Redis directly.
# 
# Reference Documentation:
# - apr-19-merit-e2e-integration.md: End-to-end integration testing and verification.

# Note: Any updates to the assistant REST API standard must be mirrored in client-merit-instructional-flow.js to ensure a smooth chat experience for both new and returning users.

# Recursive Learning Platform API Gateway Configuration
# Version: 1.0.0
# Last Updated: April 20, 2025
# Environment: Production
# Description: OpenAPI 3.0 specification for Recursive Learning Platform Mock Gateway

openapi: 3.0.0
info:
  title: Recursive Mock Gateway
  description: Recursive Learning REST API with Mock Gateway
  version: 1.0.0

servers:
  - url: https://api.recursivelearning.app/prod
    description: Production server

x-amazon-apigateway-domain-name:
  domainName: api.recursivelearning.app
  certificateArn: arn:aws:acm:us-east-2:559050208320:certificate/d1ba7f15-1f1b-400c-942e-c5e5a60ddf8c
  endpointConfiguration:
    types:
      - REGIONAL
  securityPolicy: TLS_1_2

x-amazon-apigateway-vpc-link:
  id: !Ref VpcLink
  targetArns:
    - arn:aws:elasticloadbalancing:us-east-2:718770453195:loadbalancer/app/prod-cmh-1-cdtls-1-2-100/1120e7fa7fe27cd1
    - arn:aws:elasticloadbalancing:us-east-2:718770453195:loadbalancer/app/prod-cmh-1-cdtls-1-2-133/bcb4d9ef523a5fed
    - arn:aws:elasticloadbalancing:us-east-2:718770453195:loadbalancer/app/prod-cmh-1-cdtls-1-2-252/cdaafda30bb06c0f

paths:
  /api/v1/context:
    post:
      operationId: createContext
      summary: Create or update context
      security:
        - ApiKeyAuth: []
      x-amazon-apigateway-integration:
        type: HTTP_PROXY
        uri: https://api.recursivelearning.app/prod/api/v1/context
        httpMethod: POST
        connectionType: VPC_LINK
        connectionId: !Ref VpcLink
        requestParameters:
          integration.request.header.X-Forwarded-For: context.identity.sourceIp
        responses:
          default:
            statusCode: "200"
      responses:
        "200":
          description: Success
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: CORS header
    options:
      summary: CORS support
      x-amazon-apigateway-integration:
        type: MOCK
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,x-api-key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
      responses:
        "200":
          description: CORS support
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string

  /api/v1/mock:
    get:
      operationId: getMock
      summary: Get mock response
      x-amazon-apigateway-integration:
        type: MOCK
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
            responseTemplates:
              application/json: '{"message": "Mock response successful", "timestamp": "$context.requestTimeEpoch"}'
      responses:
        "200":
          description: Success
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
    options:
      summary: CORS support
      x-amazon-apigateway-integration:
        type: MOCK
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,x-api-key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
      responses:
        "200":
          description: CORS support
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string

#-----------------------------------------------------------------------------
# Security Definitions
#-----------------------------------------------------------------------------
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-api-key
      in: header

#-----------------------------------------------------------------------------
# Error Response Configuration
#-----------------------------------------------------------------------------
x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key,Authorization'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
  DEFAULT_5XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key,Authorization'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
  UNAUTHORIZED:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key,X-Project-ID,Origin,Authorization'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
      gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
  ACCESS_DENIED:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'https://recursivelearning.app'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key,X-Project-ID,Origin,Authorization'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
      gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"

x-amazon-apigateway-api-key-source: HEADER

security:
  - ApiKeyAuth: []

x-amazon-apigateway-endpoint-configuration:
  types:
    - REGIONAL

x-amazon-apigateway-policy:
  Version: '2012-10-17'
  Statement:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource: 'arn:aws:execute-api:us-east-2:559050208320:l6lzwy3eie/*/*/*' 